In [8]:
import pandas as pd

In [9]:
df = pd.read_csv("data/subscriptions.csv")

In [10]:
# Convert relevant date columns to datetime
df['Start Date (UTC)'] = pd.to_datetime(df['Start Date (UTC)'])
df['Canceled At (UTC)'] = pd.to_datetime(df['Canceled At (UTC)'])

# Extract the month and year
df['start_month'] = df['Start Date (UTC)'].dt.to_period('M')
df['cancel_month'] = df['Canceled At (UTC)'].dt.to_period('M')

In [11]:

# Determine the full range of months in the dataset
all_months = pd.period_range(df['Start Date (UTC)'].min().to_period('M'),
                             df[['Start Date (UTC)', 'Canceled At (UTC)']].max().max().to_period('M'),
                             freq='M')

# Initialize churn metrics
monthly_churn = []

In [12]:

for month in all_months:
    # Active at beginning of month: all users who started before or in this month and not yet canceled
    active = df[
        (df['Start Date (UTC)'] <= month.start_time) &
        (
            (df['Canceled At (UTC)'].isna()) |
            (df['Canceled At (UTC)'] >= month.start_time)
        )
    ]

    # Canceled in this month
    canceled = df[df['cancel_month'] == month]

    active_count = len(active)
    canceled_count = len(canceled)

    churn_rate = canceled_count / active_count if active_count > 0 else None

    monthly_churn.append({
        'Month': month.strftime('%Y-%m'),
        'Active at Start': active_count,
        'Canceled': canceled_count,
        'Churn Rate': round(churn_rate, 4) if churn_rate is not None else None
    })

In [13]:
churn_df = pd.DataFrame(monthly_churn)

In [14]:
churn_df

      Month  Active at Start  Canceled  Churn Rate
0   2023-09                0         0         NaN
1   2023-10                1         2      2.0000
2   2023-11               12         2      0.1667
3   2023-12               22         1      0.0455
4   2024-01               25         2      0.0800
5   2024-02               25         1      0.0400
6   2024-03               33         1      0.0303
7   2024-04               41         4      0.0976
8   2024-05               48        14      0.2917
9   2024-06               49        14      0.2857
10  2024-07               48         5      0.1042
11  2024-08               50        11      0.2200
12  2024-09               51        11      0.2157
13  2024-10               60        21      0.3500
14  2024-11               65        11      0.1692
15  2024-12               64         9      0.1406
16  2025-01               77        12      0.1558
17  2025-02               94        15      0.1596
18  2025-03               91        11      0.1209
19  2025-04               95        25      0.2632
20  2025-05               84        10      0.1190
21  2025-06               82        14      0.1707
22  2025-07               81         6      0.0741